slightly refactor test_expect for operators to use correct variance
netket/netket pull request #1091
Opened 2022-02-01 15:15 UTC by PhilipVinc

This PR changes the logic used to compute the distance between two gradients (i believe the old one was partly broken).
Also the error tolerance now depends on the variance of the local energy. 

Taken from #1065 . I want to merge the changes to the tests separately and be sure you agree with them.

2022-02-01 16:30 UTC, femtobit commented
>  Also the error tolerance now depends on the variance of the local energy.

The MC standard error scales with `mcse = sqrt(variance / N)`. Is there a reason the tolerances are now given in terms of `err = variance / sqrt(N)`? (Instead of, say, a factor times `mcse`?)

2022-02-01 16:33 UTC, PhilipVinc commented
ah right, it's just my fault.

```python
err =  np.sqrt (O_stat.variance / vstate.n_samples)
```

The reason i want this instead of a constant is that when estimating the error on Squared operators (whose variance is larger) the one with `variance=5` that is now used fails.

2022-02-01 16:38 UTC, femtobit commented
Its certainly better to check whether the expectation value falls approximately into `true_value ± mcse`.

But you probably need a factor: Assuming everything has a nice Gaussian distribution, the estimate would end up outside the standard error bounds about a third of the time, right?

2022-02-01 17:45 UTC, gcarleo requested changes

2022-02-01 17:45 UTC, gcarleo commented on test/variational/test_variational.py
> -    err = 5 / np.sqrt(vstate.n_samples)
that's why here I put a 5 I think

2022-02-02 10:53 UTC, PhilipVinc commented on test/variational/test_variational.py
> +    err = O_stat1.variance / np.sqrt(vstate.n_samples)
i forgot we precompute that

2022-02-02 11:10 UTC, PhilipVinc commented on test/variational/test_variational.py
> +    der_log_mod = np.mod(der_log.imag, np.pi * 2)
Yeah I can, i was just being overly zealous...

I simplified a bit this logic now

2022-02-02 11:20 UTC, femtobit approved these changes
Looks good to me now.

2022-02-02 14:52 UTC, gcarleo commented on test/variational/test_variational.py
> +    # mod(|B-A|)
```suggestion
 # |B-A| mod 2Pi
```

2022-02-02 14:52 UTC, gcarleo approved these changes
looks good now

2022-02-02 16:53 UTC, merged