Release 3.4.2 bugfix release
netket/netket pull request #1190
Opened 2022-05-05 13:52 UTC by PhilipVinc

2022-05-05 14:45 UTC, femtobit commented
@PhilipVinc I'd like to add the correction we discussed to the changelog, while we're add it. Is this okay (see my commit)?

2022-05-05 16:21 UTC, PhilipVinc commented
yes it's good for me 
(I still want to fix a few more of those dtype things before releasing)

2022-05-06 14:30 UTC, femtobit requested changes
Looks good to me.

2022-05-06 14:30 UTC, femtobit commented on CHANGELOG.md
> +* `nkx.TDVP` now updates the expectation value displaied in the progress bar at every time-step. [#1182](https://github.com/netket/netket/pull/1182)
```suggestion
* `nkx.TDVP` now updates the expectation value displayed in the progress bar at every time step. [#1182](https://github.com/netket/netket/pull/1182)
```

2022-05-06 14:30 UTC, femtobit commented on CHANGELOG.md
>  * Fixed bug [#1192](https://github.com/netket/netket/pull/1192) that affected most operators (`nk.operator.LocalOperator`) constructed on non-homogeneous hilbert spaces. This bug was first introduced
```suggestion
* Fixed bug [#1192](https://github.com/netket/netket/pull/1192) that affected most operators (`nk.operator.LocalOperator`) constructed on non-homogeneous hilbert spaces. This bug was first introduced in version 3.3.4 and affects all subsequent versions until 3.4.2. [#1193](https://github.com/netket/netket/pull/1193)
```

2022-05-06 16:06 UTC, femtobit approved these changes

2022-05-08 19:40 UTC, gcarleo approved these changes

2022-05-08 19:47 UTC, merged