Stop when loss is NaN
netket/netket pull request #1239
Opened 2022-06-10 16:05 UTC by VolodyaCO

Closes #1222

This PR includes the `InvalidLossStopping` callback. As mentioned in #1222, I once saw energy going to NaN and back to being finite. Thus, we might want to not have this as default. I was thinking, however, that we can have a "default" callback that checks for NaNs in the loss value, and if it sees NaNs, it raises a warning, telling the user that they might want to include this callback.

Seems too cumbersome, though. What do you think about it?

2022-06-17 14:14 UTC, femtobit requested changes
The current test failures are just because `InvalidLossStoping` is used as default callback instead of `InvalidLossStoping()`.

Beside that, I have two comments:

2022-06-17 14:14 UTC, femtobit commented on netket/driver/abstract_variational_driver.py
> +        callback=InvalidLossStopping,
Providing this as the default callback has the downside that if users pass their own callbacks, they can inadvertently remove the invalid loss stopping.

One option to still include it by default (and allow users to remove it) would be to set the default `callback=[]` and add something like
```python3
if stop_on_invalid_loss and all(not isinstance(cb, InvalidStopLoss) for cb in callback):
    callback.append(InvalidStopLoss())
```
depending on a new argument `stop_on_invalid_loss: bool`.

2022-06-17 14:14 UTC, femtobit commented on netket/callbacks/invalidlossstopping.py
> +class InvalidLossStopping:
It could be nice if this too had a `patience` property, so the criterion can be configured to only abort if the loss is invalid for several steps.

2022-06-24 07:55 UTC, PhilipVinc reviewed
@VolodyaCO I'm convinced about the usefulness of `InvalidLossStop` callback, but I'm less convinced about bolting it in the `AbstractDriver.run` Interface, as it's some added complexity that could be shared among several drivers and I'm unsure that's the best place to put it.

I would be very happy if you could split the `InvalidLossStopping` out of this PR into a separate one (+ tests and a notice in changelog) and I will quickly merge it.

Then, this Pr here would be only about correctly integrating this callback into the default driver, and I'll take some time to think about it.

2024-08-28 16:23 UTC, PhilipVinc commented
The callback was merged. The Driver interface was not changed

2024-08-28 16:23 UTC, closed without merging