Chunking apply_fun for MCState.to_array
netket/netket pull request #1470
Opened 2023-05-04 13:06 UTC by alleSini99

`MCState.to_array()` cannot be used to instantiate the wave function over the full Hilbert space for systems with fairly large size (but that should be still accessible) due to a large memory usage. The modification in `MCState.to_array()` consists in the possibility of computing the wave function over chunk of the Hilbert space of size `MCState.chunk_size` that are then combined to get the complete state vector.

2023-05-04 13:20 UTC, PhilipVinc requested changes
Nice! can you also do the same for the the mixed state (`to_array` and `to_matrix`)?

Anyhow, unfortunately `apply_chunked`returns a closure that changes hash every time you run it, so this will trigger recompilation every time you execute `to_array()`.

To fix this you should go to `_vmap_chunked.py` and make sure that the function returned from `_chunk_vmapped_function` has a constant hash and equality.

In essence you want to make sure that the following test pass:
```python
f1a = nk.jax.apply_chunked(fun, chunk_size=10)
f1b = nk.jax.apply_chunked(fun, chunk_size=10)
f2 = nk.jax.apply_chunked(fun, chunk_size=20)

assert f1a == f1b
assert hash(f1a) == hash(f1b)
assert f1a != f2
assert hash(f1a) != hash(f2)
```

2023-05-04 13:20 UTC, PhilipVinc commented on netket/vqs/mc/mc_state/state.py
> +            self.hilbert, nk.jax.apply_chunked(self._apply_fun, in_axes=(None, 0), chunk_size=self.chunk_size), self.variables, normalize=normalize
```suggestion
            self.hilbert, nkjax.apply_chunked(self._apply_fun, in_axes=(None, 0), chunk_size=self.chunk_size), self.variables, normalize=normalize
```

2023-05-07 13:10 UTC, PhilipVinc commented
Actually the easiest solution would be to just add a `chink_size` keyword argument defaulting to `None` to `nk.nn.to_array`, and use the `nkjax.apply_chunked` from inside the fitted function.

2023-05-08 07:01 UTC, inailuig commented on netket/nn/utils.py
> +        apply_fun = nkjax.apply_chunked(apply_fun, in_axes=(None, 0), chunk_size=chunk_size)
apply_chunked already returns the original function if chunk_size is None...

```suggestion
    apply_fun = nkjax.apply_chunked(apply_fun, in_axes=(None, 0), chunk_size=chunk_size)
```

2023-05-08 07:03 UTC, inailuig commented
> Anyhow, unfortunately `apply_chunked`returns a closure that changes hash every time you run it, so this will trigger recompilation every time you execute `to_array()`.
> 
> To fix this you should go to `_vmap_chunked.py` and make sure that the function returned from `_chunk_vmapped_function` has a constant hash and equality.
> 
> In essence you want to make sure that the following test pass:
> 
> ```python
> f1a = nk.jax.apply_chunked(fun, chunk_size=10)
> f1b = nk.jax.apply_chunked(fun, chunk_size=10)
> f2 = nk.jax.apply_chunked(fun, chunk_size=20)
> 
> assert f1a == f1b
> assert hash(f1a) == hash(f1b)
> assert f1a != f2
> assert hash(f1a) != hash(f2)
> ```

Decided to fix this while we are at it..

2023-05-08 08:42 UTC, PhilipVinc commented
Black?

2023-05-08 14:11 UTC, PhilipVinc approved these changes
great, thanks!

2023-05-08 14:11 UTC, merged