Make ExchangeSampler only propose different configurations
netket/netket pull request #1815
Opened 2024-05-27 16:08 UTC by PhilipVinc

This was implemented by @jwnys for Fermionic states, but makes sense in general for the ExchangeRule in general.

2024-05-28 17:24 UTC, jwnys requested changes
Looks good

2024-05-28 17:24 UTC, jwnys commented on netket/sampler/rules/exchange.py
> +def _compute_different_clusters_mask(clusters, σ):
Here we could maybe check 
```python
if jnp.issubdtype(σ.dtype, int):
    hoppable_clusters_mask = σ[..., clusters[:, 0]] != σ[..., clusters[:, 1]]
else:
    hoppable_clusters_mask = ~jnp.isclose(
        σ[..., clusters[:, 0]], σ[..., clusters[:, 1]]
    )

2024-05-28 17:30 UTC, jwnys commented
Thinking a bit more about this, maybe we should impose some more checks?
- For bosons or Fock space different than the fermionic one: if this is a single boson move or "exchange", an exchange would check something different.
- For higher spin components, there are more moves allowed that maintain the Sz that should be considered.

2024-05-28 17:36 UTC, gcarleo requested changes
if I understand correctly this does random permutations of the local occupations ? however this is not general,we should rather do a random choice of the local two site configurations such that the total number is locally conserved.(unless I misunderstood the implementation)

2024-05-29 06:19 UTC, gcarleo commented
yes but these simple exchange moves are not ergodic, for local Hilbert spaces with more than two states, not sure we should have a warning in those cases ?

2024-05-29 06:30 UTC, PhilipVinc commented
That's already the case...

2024-05-29 06:32 UTC, PhilipVinc commented
As for warnings, yes, I've long agreed.
As usual someone must do it

2024-05-29 06:42 UTC, gcarleo commented
ok, but yes I actually agree that being an exchange sampler the
implementation you are using is ok. we should add warnings more generally
but indeed it's a lot more work because we need to touch all samplers and
check consistency. The more general MetropolisHop or similar has already
been implemented by Zakari, maybe he could do a PR with that

On Wed, May 29, 2024, 08:32 Filippo Vicentini ***@***.***>
wrote:

> As for warnings, yes, I've long agreed.
> As usual someone must do it
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/netket/netket/pull/1815#issuecomment-2136639440>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGWYRBEQKUQGSSDGRIXFUC3ZEVZARAVCNFSM6AAAAABILOMMECVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMZWGYZTSNBUGA>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2024-05-29 06:44 UTC, gcarleo approved these changes

2024-05-29 06:49 UTC, PhilipVinc commented
I think that having a proper 'hopping' rule is the way to go.
With possibility to 'hop' 1,2 or N values at a time.

We can keep this exchange kernel around for local size 2 (because it is simpler and probably faster) and as an example, but also because it might make sense to use it.

2024-05-29 18:27 UTC, merged